version: 0.0
os: linux
files:
- source: target/helloworld.war
  destination: /home/ec2-user/webapp
# - source: /scripts/requirements.txt
#   destination: /home/ec2-user/scripts
hooks:
  AfterInstall:
  - location: scripts/deployment
    timeout: 300
    runas: root
#   - location: scripts/install_tomcat
#     timeout: 300
#     runas: root
#   - location: scripts/install_httpd
#     timeout: 300
#     runas: root
#   ApplicationStart:
#   - location: scripts/start_server
#     timeout: 300
#     runas: root
#  ApplicationStop:
#  - location: scripts/stop_server
#    timeout: 300
#    runas: root
