#!/bin/bash

# Install dos2unix
sudo yum install -y dos2unix

# Convert the line endings of the install_java script to Linux format
dos2unix scripts/install_java

# Run the install_java script to install Java
bash scripts/install_java

# Install OpenJDK 8
sudo yum install -y java-1.8.0-openjdk

# Set environment variables for Java
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
export PATH=$PATH:$JAVA_HOME/bin

# Install Maven
sudo yum install -y maven

# Set environment variables for Maven
export M2_HOME=/usr/share/maven
export MAVEN_HOME=/usr/share/maven
export PATH=$PATH:$MAVEN_HOME/bin

# Install Tomcat server
sudo yum install -y tomcat tomcat-webapps tomcat-admin-webapps

# Configure Tomcat server
sudo sed -i 's|</tomcat-users>|  <role rolename="manager-gui"/>\n  <user username="admin" password="password" roles="manager-gui"/>\n</tomcat-users>|' /usr/share/tomcat/conf/tomcat-users.xml

# Restart Tomcat server
sudo service tomcat restart

# Clone the Maven project from Git repository
git clone https://github.com/SamynathanS6720/Java-Wep-app-Pipeline

# Navigate to the Maven project directory
cd Java-Wep-app-Pipeline/

# Build the Maven project
mvn clean package

# Copy the WAR file to Tomcat webapps directory
sudo cp target/project.war /usr/share/tomcat/webapps/

# Restart Tomcat server to deploy the project
sudo service tomcat restart
